### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by NeonSpectrum** [NeonSpectrum/tnt#6]
- [ ] Export Final Scores to PDF

- [ ] Viewer Module

- [ ] Autopilot Option

- [ ] See Current Question in Control Panel

- [ ] Import Excel File for Questionnaires

- [ ] Greyed-out in scoreboard if college is not online
